name: Deploy Next.js Application

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      # Add any additional steps here, such as running tests or linting

      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /supersoft/mpm-web
            if [ ! -d ".git" ]; then
              git clone https://github.com/your_username/your_repository.git .
            else
              git pull origin main
            fi
            npm install
            npm run dev
            # Add any additional commands needed for deployment
